import { describe, it, expect } from 'vitest';
import {
  mkdtempSync, readFileSync, existsSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildEcdsaSdIssuer } from '../scripts/seed/ecdsa-sd-signing';
import { verifyDpp, dppIsAuthentic } from '../src/crypto/dispatch';
import { decodeMultibaseBase58 } from '../src/crypto/multibase';

// Resolve each proof's key from the emitted Multikey doc: the
// platform proof verifies against platform-p256.json, every
// other against issuer-p256.json.
function keyResolver(keysDir: string): (m: string) => Promise<Uint8Array> {
  const load = (fileName: string): Uint8Array => decodeMultibaseBase58(
    (JSON.parse(readFileSync(join(keysDir, fileName), 'utf8')) as
      { publicKeyMultibase: string }).publicKeyMultibase,
  );
  return (method: string): Promise<Uint8Array> => Promise.resolve(
    method.endsWith('platform-p256.json')
      ? load('platform-p256.json') : load('issuer-p256.json'),
  );
}

describe('seed ecdsa-sd issuer', () => {
  it('issues a VC with two proofs the verifier accepts', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'sd-'));
    const issuer = await buildEcdsaSdIssuer(
      dir, 'acme', 'abc12345', '2026-05-01T12:00:00Z',
      'did:web:acme.example', 'did:web:platform.example',
    );
    const body = {
      '@context': ['ignored'],
      '@type': 'dpp:DigitalProductPassport',
      '@id': 'https://acme.example/dpp/abc12345',
      passportAlias: 'abc12345',
      version: 1,
      product: {
        '@type': 'Product',
        name: 'Pulse 2000',
        properties: [
          {
            '@type': 'PropertyValue', propertyID: 'capacity',
            name: 'Capacity', value: '2.0',
          },
        ],
      },
    };
    const vc = await issuer.issue(body);
    expect((vc.proof as unknown[]).length).toBe(2);
    const v = await verifyDpp(vc, {
      resolveIssuerKey: keyResolver(join(dir, 'acme/dpp/abc12345/keys')),
    });
    expect(v.cryptosuite).toBe('ecdsa-sd-2023');
    expect(dppIsAuthentic(v)).toBe(true);
  });
});

// The seed's actual output lives under public/ (gitignored,
// regenerated by `npm run seed`), so this only runs where a
// seed has been produced; CI without one skips it.
const SEEDED = fileURLToPath(new URL(
  '../public/volturra-pulse-2000/dpp/demo-2026-b001', import.meta.url,
));

describe.skipIf(!existsSync(join(SEEDED, 'v/1.json')))(
  'seed ecdsa-sd: produced Volturra artefact', () => {
    it('verifies both proofs of the served snapshot', async () => {
      const vc = JSON.parse(readFileSync(join(SEEDED, 'v/1.json'), 'utf8'));
      const v = await verifyDpp(vc, {
        resolveIssuerKey: keyResolver(join(SEEDED, 'keys')),
      });
      expect(v.cryptosuite).toBe('ecdsa-sd-2023');
      expect(dppIsAuthentic(v)).toBe(true);
    });
  },
);
